# Lightweight development setup using only SQLite and ChromaDB
version: '3.8'

services:
  # MCP Memory Server (Lightweight Mode)
  mcp-memory-server-lite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contextra-mcp-server-lite
    ports:
      - "${MCP_PORT:-8000}:8000"
    environment:
      # Lightweight Configuration
      LIGHTWEIGHT_MODE: true
      MCP_DEBUG: ${MCP_DEBUG:-true}
      ENABLE_AUTO_SYNTHESIS: ${ENABLE_AUTO_SYNTHESIS:-true}
      DEFAULT_EMBEDDING_MODEL: ${DEFAULT_EMBEDDING_MODEL:-all-MiniLM-L6-v2}
      MAX_SEARCH_RESULTS: ${MAX_SEARCH_RESULTS:-10}
      
      # SQLite Configuration (no external database needed)
      SQLITE_PATH: /app/data/contextra.db
      
      # ChromaDB Configuration (no external vector DB needed)
      CHROMADB_PATH: /app/data/chromadb
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  contextra-network:
    driver: bridge
